# Generated by Django 4.2.13 on 2024-05-31 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edad", models.PositiveIntegerField()),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Mujer"), ("H", "Hombre"), ("NB", "No Binario")],
                        default="Hombre",
                        max_length=100,
                    ),
                ),
                (
                    "foto_perfil",
                    models.ImageField(blank=True, null=True, upload_to="fotos_perfil"),
                ),
                ("biografia", models.TextField()),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Colaborador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Imagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="imagenes"),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="colaborador.colaborador",
                    ),
                ),
            ],
            options={
                "ordering": ("fecha_subida",),
            },
        ),
    ]
