# Generated by Django 4.2.13 on 2024-06-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colaborador", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colaborador",
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
            },
        ),
        migrations.AlterModelOptions(
            name="imagen",
            options={
                "ordering": ("fecha_subida",),
                "verbose_name": "Imagen",
                "verbose_name_plural": "Imagenes",
            },
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="genero",
            field=models.CharField(
                choices=[("Mujer", "M"), ("Hombre", "H"), ("NoBinario", "NB")],
                default="Hombre",
                max_length=100,
            ),
        ),
    ]
